services:
  # Web service
  - type: web
    name: url-shortener
    env: python
    rootDir: HW3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
    envVars:
      - key: POSTGRES_USER
        fromDatabase:
          name: url-shortener-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: url-shortener-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: url-shortener-db
          property: database
      - key: POSTGRES_HOST
        fromDatabase:
          name: url-shortener-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: url-shortener-db
          property: port
      - key: SECRET_KEY
        generateValue: true
      - key: TESTING
        value: "False"
      - key: REDIS_HOST
        fromService:
          name: url-shortener-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: url-shortener-redis
          type: redis
          property: port

  # Redis service
  - type: redis
    name: url-shortener-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

# Database
databases:
  - name: url-shortener-db
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
